version: '3'

services:
  fnc-db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_USERNAME: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: shorti_db
  shorti-service:
    build:
      context: shorti-service
      dockerfile: ./Dockerfile
    image: "shorti/service"
    environment: 
      SHORTI_DB_URL: jdbc:mysql://shorti-db:3306/shorti_db
    ports:
      - "4080:8080"
  shorti-app:
    build:
      context: shorti-app
      dockerfile: ./Dockerfile
    image: "shorti/app"
    ports:
      - "4000:80"