#spring:
#  datasource:
#    url: ${SHORTI_DB_URL}
#    username: root
#    password: root
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    ddl-auto: update

spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
